[package]
name = "slint-rust-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.8.0"
rfd = "0.15.1"
crossbeam = "0.8.4"
network-initializer = { git = "ssh://git@github.com/Rusteze-AP/network-initializer.git", branch = "main" }
wg_internal = { git = "https://github.com/Rusteze-AP/RS_WGL_2024", branch = "local_changes" }
rusteze_drone = { git = "ssh://git@github.com/Rusteze-AP/drone.git", branch = "main" }
client = { git = "ssh://git@github.com/Rusteze-AP/client-server-testing.git", branch = "main" }
server = { git = "ssh://git@github.com/Rusteze-AP/client-server-testing.git", branch = "main" }
logger = { git = "https://github.com/Rusteze-AP/logger.git", branch = "main" }


[build-dependencies]
slint-build = "1.8.0"