[package]
name = "slint-rust-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.8.0"
network-initializer = { path = "../network-initializer" }
wg_internal = { git = "https://github.com/Rusteze-AP/RS_WGL_2024", branch = "add-nackType" }
rusteze_drone = { path = "../drone/" }
client = { path = "../client-server-testing/src/dependencies/client" }
server = { path = "../client-server-testing/src/dependencies/server" }
rfd = "0.15.1"
crossbeam = "0.8.4"

[build-dependencies]
slint-build = "1.8.0"