[[drones]]
id = 1
connected_drone_ids = [2,6,20]
pdr = 0.2

[[drones]]
id = 2
connected_drone_ids = [1,3,7]
pdr = 0.2

[[drones]]
id = 3
connected_drone_ids = [2,4,8]
pdr = 0.1

[[drones]]
id = 4
connected_drone_ids = [3,5,9]
pdr = 0.2

[[drones]]
id = 5
connected_drone_ids = [4,10,30,31]
pdr = 0.1

[[drones]]
id = 6
connected_drone_ids = [1,7,21]
pdr = 0.3

[[drones]]
id = 7
connected_drone_ids = [2,6,8]
pdr = 0.3

[[drones]]
id = 8
connected_drone_ids = [3,7,9]
pdr = 0.3

[[drones]]
id = 9
connected_drone_ids = [4,8,10]
pdr = 0.1

[[drones]]
id = 10
connected_drone_ids = [5,9,30,31]
pdr = 0.3

[[clients]]
id = 20
connected_drone_ids = [1]

[[clients]]
id = 21
connected_drone_ids = [6]

[[servers]]
id = 30
connected_drone_ids = [5,10]

[[servers]]
id = 31
connected_drone_ids = [5,10]
