[[drones]]
id = 0
connected_drone_ids = [1, 2, 4]
pdr = 0.05

[[drones]]
id = 1
connected_drone_ids = [0, 5, 20, 30]
pdr = 0.03

[[drones]]
id = 2
connected_drone_ids = [0, 7, 20]
pdr = 0.02

[[drones]]
id = 3
connected_drone_ids = [30, 31]
pdr = 0.05

[[drones]]
id = 4
connected_drone_ids = [0, 5, 6]
pdr = 0.07

[[drones]]
id = 5
connected_drone_ids = [1, 4, 8]
pdr = 0.1

[[drones]]
id = 6
connected_drone_ids = [4, 31]
pdr = 0.075

[[drones]]
id = 7
connected_drone_ids = [2, 9, 20]
pdr = 0.3

[[drones]]
id = 8
connected_drone_ids = [5, 9]
pdr = 0.002

[[drones]]
id = 9
connected_drone_ids = [7, 8]
pdr = 0.043

[[clients]]
id = 20
connected_drone_ids = [1, 2, 7]

[[servers]]
id = 30
connected_drone_ids = [1, 3]

[[servers]]
id = 31
connected_drone_ids = [3, 6]
