[[drones]]
id = 0
connected_drone_ids = [1, 2]
pdr = 0.05

[[drones]]
id = 1
connected_drone_ids = [0, 3, 4]
pdr = 0.03

[[drones]]
id = 2
connected_drone_ids = [0]
pdr = 0.02

[[clients]]
id = 3
connected_drone_ids = [1]

[[servers]]
id = 4
connected_drone_ids = [1]
