[[drones]]
id = 0
connected_drone_ids = [1, 2, 3]
pdr = 0.05

[[drones]]
id = 1
connected_drone_ids = [0, 4, 20, 30]
pdr = 0.03

[[drones]]
id = 2
connected_drone_ids = [0, 20]
pdr = 0.02

[[drones]]
id = 3
connected_drone_ids = [0, 20]
pdr = 0.02

[[drones]]
id = 4
connected_drone_ids = [1, 20, 21]
pdr = 0.02

[[drones]]
id = 5
connected_drone_ids = [30]
pdr = 0.01

[[drones]]
id = 6
connected_drone_ids = [30]
pdr = 0.02

[[drones]]
id = 7
connected_drone_ids = [8, 30]
pdr = 0.02

[[drones]]
id = 8
connected_drone_ids = [7, 30, 31]
pdr = 0.02

[[drones]]
id = 9
connected_drone_ids = [30, 31]
pdr = 0.02

[[clients]]
id = 20
connected_drone_ids = [1, 2, 3, 4]

[[clients]]
id = 21
connected_drone_ids = [4]

[[servers]]
id = 30
connected_drone_ids = [1, 5, 6, 7, 8, 9]

[[servers]]
id = 31
connected_drone_ids = [8, 9]
