[[drones]]
id = 0
connected_drone_ids = [1, 2]
pdr = 0.05

[[drones]]
id = 1
connected_drone_ids = [0, 20, 30]
pdr = 0.03

[[drones]]
id = 2
connected_drone_ids = [0, 20]
pdr = 0.02

[[clients]]
id = 20
connected_drone_ids = [1, 2]

[[servers]]
id = 30
connected_drone_ids = [1]
