[[drones]]
id = 1
connected_drone_ids = [2, 7]
pdr = 0.1

[[drones]]
id = 2
connected_drone_ids = [1, 3, 7]
pdr = 0.1

[[drones]]
id = 3
connected_drone_ids = [2, 4, 8, 9]
pdr = 0.1

[[drones]]
id = 4
connected_drone_ids = [3, 5, 8, 9]
pdr = 0.1

[[drones]]
id = 5
connected_drone_ids = [4, 6, 10]
pdr = 0.1

[[drones]]
id = 6
connected_drone_ids = [5, 10]
pdr = 0.1

[[drones]]
id = 7
connected_drone_ids = [1, 2, 20, 8]
pdr = 0.1

[[drones]]
id = 8
connected_drone_ids = [3, 4, 7, 9, 30]
pdr = 0.1

[[drones]]
id = 9
connected_drone_ids = [3, 4, 8, 10, 30]
pdr = 0.1

[[drones]]
id = 10
connected_drone_ids = [5, 6, 9, 21]
pdr = 0.1

[[clients]]
id = 20
connected_drone_ids = [7]

[[clients]]
id = 21
connected_drone_ids = [10]

[[servers]]
id = 30
connected_drone_ids = [8, 9]
