[[drones]]
id = 1
connected_drone_ids = [2,3]
pdr = 0.1

[[drones]]
id = 2
connected_drone_ids = [1,4,5,6]
pdr = 0.1

[[drones]]
id = 3
connected_drone_ids = [1,4,5,6]
pdr = 0.1

[[drones]]
id = 4
connected_drone_ids = [2,3,7,8,9,10]
pdr = 0.1

[[drones]]
id = 5
connected_drone_ids = [2,3,7,8,9,10]
pdr = 0.1

[[drones]]
id = 6
connected_drone_ids = [2,3,7,8,9,10]
pdr = 0.1

[[drones]]
id = 7
connected_drone_ids = [4,5,6,20]
pdr = 0.1

[[drones]]
id = 8
connected_drone_ids = [4,5,6,21]
pdr = 0.1

[[drones]]
id = 9
connected_drone_ids = [4,5,6,30]
pdr = 0.1

[[drones]]
id = 10
connected_drone_ids = [4,5,6,30]
pdr = 0.1

[[clients]]
id = 20
connected_drone_ids = [7]

[[clients]]
id = 21
connected_drone_ids = [8]

[[servers]]
id = 30
connected_drone_ids = [9,10]
